import Header from "@/components/global/header/Header";
import "./globals.css";
import { Roboto } from "next/font/google";
import { AppProvider } from "@/context/context";
import { AuthContextProvider } from "@/context/authContext";
import { Suspense } from "react";
import Spinner from "@/components/global/loader/Spinner";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/global/footer/footer";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AppProvider>
      <AuthContextProvider>
        <html lang="en">
          <body
            className={`${roboto.className}`}
            suppressHydrationWarning={true}
          >
            <Suspense fallback={<Spinner />}>
              <main>
                <Header />
                <div className=" bg-slate-50 min-h-[calc(100vh-1.25rem)] text-black">
                  {children}
                </div>
                <Footer />
              </main>
              {/* <Loader /> */}
              <ToastContainer />
            </Suspense>
          </body>
        </html>
      </AuthContextProvider>
    </AppProvider>
  );
}
